apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: kube-auth-proxy

build:
  tagPolicy:
    gitCommit:
      variant: Tags
  local:
    push: false
    useBuildkit: true
  artifacts:
  - image: kube-auth-proxy
    docker:
      dockerfile: Dockerfile
      buildArgs:
        VERSION: "{{.IMAGE_TAG}}"

profiles:
- name: e2e
  manifests:
    rawYaml:
    - test/e2e/manifests/*.yaml
  deploy:
    kubeContext: kind-cluster-a
    kubectl:
      defaultNamespace: kube-auth-proxy-e2e
