apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: kube-auth-proxy

build:
  tagPolicy:
    gitCommit:
      variant: Tags
  local:
    push: false
    useBuildkit: true
  artifacts:
  - image: kube-auth-proxy
    docker:
      dockerfile: Dockerfile
      buildArgs:
        VERSION: "{{.IMAGE_TAG}}"

manifests:
  rawYaml:
  - test/e2e/manifests/*.yaml

deploy:
  kubectl:
    defaultNamespace: kube-auth-proxy
